# NumPy Exercise



This is taken from Wie Kiang H.
https://towardsdatascience.com/data-science-with-python-how-to-use-numpy-library-5885aa83be6b

In [61]:
#to install numpy using pip
!pip install numpy

Load the numpy library



In [10]:
import numpy as np

# — array

Numpy¹ array essentially comes in two flavors, one-dimensional vectors or two-dimensional matrices. They can both be called an array. Vectors are strictly one-dimension array and matrices are two-dimensional array. Also, note that a matrix can still only have one row or one column.

In [12]:
list_of_numbers = [1,2,3]
arr = np.array(list_of_numbers)
print(arr)

[1 2 3]


In [14]:
list_of_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We might see that list can be used as an array. Additionally, we can assign an array to a variable.

# — arange

This is really similar to Python’s built-in range function. It is represented with a syntax np.arrange and then passes in a start and stop value. Notice that we have a start, stop, and step size in the third argument. It will return evenly spaced values within the given interval. If we just put it from 0 to 10, remember just like in Python that range indexing starts at 0. It will return a value from 0 up to but not including 10. As a result, we will get an array back from 0 all the way up to 9, it is a 10 digits number. If we want to get the value from 0 all the way to 10, we have to type np.arange(0,11).

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Finally, we can add a third argument, which is a step size. For example, we want an array of even numbers from 0 to 10. We could insert an argument 0,11. Following a step size of 2. So that, it will jump in steps of 2. All in all, a range is going to be one of the most useful functions for quickly generating an array using NumPy.

# — zeros and ones

NumPy can generate another type of array. For instance, if we want to generate arrays of all 0, we can use zeros method. We can pass in a single-digit or tuple. For a single digit, it will give a result of a dimensional vector. In tuple, on the other hand, the first number is going to represent the number of rows and the second number in that tuple is going to represent the number of columns. For example, to generate 3 rows by 4 columns we can pass in the tuple (3,4).

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Furthermore, to generate pure ones, we can call method ones. Similarly, we can pass in either a single number for a one-dimensional array or a tuple of dimension for a two-dimensional matrix.

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# — linspace

The other really useful built-in function is linspace. This function will return evenly spaced numbers over a specified interval. It is important not to confuse between linspace and arange which we have been discussed before. We can see that arange basically returns integers out from a start, stop, and given step size, while linspace is going to take a third argument of the number as points we want.

For example, we have a start of 0 and a stop of 5 in linspace and we want to get 10 evenly spaced points between 0 to 5. We can pass in a third argument 10. This command will return back a one-dimensional vector noted by the set of brackets of 10 evenly spaced points from 0 to 5.

Moreover, we can change the third argument to whatever number. For instance, if we want 100 evenly spaced points from 0 to 5, we can pass that number in the third argument. This will returns a much larger one-dimensional array. Even though it looks like a two-dimensional array, it is one-dimensional by the fact that there is only one bracket in front of the array.

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

Keep note, when we were dealing with two dimensions we will see that they have two sets of brackets on the opening or closing at the ends. Three dimensions will have three brackets and so on.

# — eye

We can use eye to create an identity matrix using NumPy. We only need to pass a single digit in the argument. The identity matrix is a useful matrix when dealing with linear algebra problems. It is basically a two-dimensional square matrix, in which the number of rows is the same as a number of columns. It has a diagonal of ones and everything else is zeros. This is the reason it only takes a single digit as an argument. The identity matrix must be square as the output of np.eye.

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# — random.rand

NumPy also has lots of ways to create an array of random numbers. The first one is random.rand. This command is going to create an array from the given shape. It is going to populate with random samples from a uniform distribution, over 0 to 1. If we want eight one-dimensional arrays of random numbers uniformly distributed from 0 to 1, we can give a number 8 in the argument. However, we can pass in the dimensions as separate arguments to get a two-dimensional array. For instance, if we want a 5x5 matrix of random numbers, we pass 5,5 instead of a tuple in the argument.

In [25]:
np.random.rand(8)

array([0.07789724, 0.28649927, 0.64432387, 0.06218797, 0.06260633,
       0.34890409, 0.91738433, 0.69264981])

In [26]:
np.random.rand(5,5)

array([[0.51928536, 0.62501053, 0.11541673, 0.70469722, 0.70268122],
       [0.57074659, 0.93987756, 0.68676625, 0.49590073, 0.5380121 ],
       [0.68451998, 0.00452096, 0.55730997, 0.07161046, 0.10338339],
       [0.48427485, 0.48389618, 0.91598182, 0.91598103, 0.89906484],
       [0.00668818, 0.17600805, 0.08723096, 0.29940205, 0.38191527]])

# — random.randn

Secondly, instead of using rand, we can use randn to return a sample or many samples from the standard normal distribution or Gaussian distribution. This will not return numbers from a uniform distribution from 0 to 1, however, it will return numbers from a standard normal distribution center around 0. Furthermore, to get a two-dimensional array, we can pass in two dimensions argument. For example, to generate a 4x4, we can pass an argument 4,4. Keep in mind that this argument is not a tuple. This is a separate argument and we can realize from the output given by the set of two brackets, which is a two-dimensional matrix.

In [27]:
np.random.randn(5)

array([ 0.48516833,  0.13817559,  0.87041407,  0.02581859, -0.39768527])

In [28]:
np.random.randn(4,4)

array([[-0.77814862, -0.96218184,  0.72254149,  0.49670961],
       [-0.93026571,  1.09245579,  0.23853989,  1.70734348],
       [-0.26439132,  0.97695684,  0.29217115,  0.10120451],
       [ 0.45918896,  0.93006937, -0.2519507 ,  0.36190089]])

# — random.randint

The final random method of creating an array is randint. This will returns random integers from a low to a high number. For instance, if we insert 1,100 in the argument, we will get a random integer between 1 and 100. The low number is inclusive, while the high number is exclusive. The number 1 has the chance of being selected but 100 is not. Additionally, if we want a particular number of random integers, we can pass the argument in the third argument.

In [29]:
np.random.randint(1, 100)

18

In [30]:
np.random.randint(1, 100, 10)

array([ 1, 53,  3, 87, 51, 48,  6, 38, 15, 56])

# — reshape

One of the most useful methods we can use on an array is the reshape method. This method is going to return an array containing the same data in a new shape. For example, if we want to reshape an array which contains 24 digits. We can reshape the 24 digits array using reshape to 4x6 array and passing the number of rows and the number of columns in the argument. Keep in mind that we will get an error if we can not fill up the matrix completely. For instance, if we want to reshape 24 elements, the total number of the new shape must be the same as 24 elements in the array.

In [31]:
arr = np.random.randint(1, 100, 24)
print(arr)

[22 66 54 81 62 82 83 80 72 14 55 92 15 35 26 66  4 13 41  9  2 16 29 25]


In [32]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [33]:
arr.reshape(4,6)

array([[22, 66, 54, 81, 62, 82],
       [83, 80, 72, 14, 55, 92],
       [15, 35, 26, 66,  4, 13],
       [41,  9,  2, 16, 29, 25]])

# — max and min

If we want to find the max value in an array, we can call the max method and this will return the maximum value of that array. Similarly, if we want to get the minimum value of the array, we can call the min method.

In [35]:
arr = np.random.randint(0, 100, 24)
print(arr)

[41 93 16 23 23 23 16 92 94 45 17 33  5 20 48 89 38 17 15 76 10 34 56 28]


In [36]:
arr.max()

94

In [37]:
arr.min()

5

# — argmax and argmin

Moreover, we can actually figure out the location of the maximum or minimum values by specifying argmax or argmin method. If we want to actually know what the index value of the maximum number, we can call argmax and it will return the index location of the maximum value. On the other hand, we can do the same thing with the minimum value. We can call argmin and it will return the index location of the minimum value.

In [39]:
arr = np.random.randint(0, 100, 24)
print(arr)

[97 19 98 45  5 47 22 11 74 90 50 95 86 70  7 45 90 12 43 30 48 57 70 55]


In [40]:
arr.argmax()

2

In [41]:
arr.argmin()

4

# — shape

If we want to figure out the shape of the vector, we can call method shape and it will return back the shape. If it is a one-dimensional vector, it will give us a result of the number of the elements following by a comma.

In [43]:
arr = np.random.randint(0, 100, 24)
print(arr)

[96 73 32 87 88 32 49 63 57 99 85 76 15 35 97  3 79 53 52 19 98 82 41  6]


In [44]:
arr.shape

(24,)

In [46]:
arr = arr.reshape(4, 6)

In [47]:
arr.shape

(4, 6)

# — dtype

The other useful attribute is the data type in an array. If we were ever curious about what data type we have in an array, we can call dtype as an attribute and it will return the actual data type of the array.

In [48]:
arr.dtype

dtype('int32')

# Indexing and Selection

The easiest way to grab one or some elements from a NumPy array is by using brackets and slice notation. Let start with declaring a variable name of the array itself; in this case, we call it my_array.

In [50]:
my_array = np.arange(10, 100, 8)
print(my_array, '\n')

print(my_array[8])
print(my_array[1:5])
print(my_array[0:5])
print(my_array[:5])
print(my_array[5:])

[10 18 26 34 42 50 58 66 74 82 90 98] 

74
[18 26 34 42]
[10 18 26 34 42]
[10 18 26 34 42]
[50 58 66 74 82 90 98]


To return a single value from a specific index from the array, you can define an argument inside the square brackets, for example, my_array[8] to get value from index 8. On the other hand, to get the values in a range like a python list, you can use slice notation. We need to define the starting index and the stop index.

For instance, my_array[1:5], will return the value from index 1 and go all the way up to index 5. Remember from the earlier explanation, in the arange section, that the second argument value is not included in indexing because the index starts from 0. To show another example of this, you can type my_array[0:5], and this will returns the values from index 0 up to index 5.

You can also remove the stop point or the start point to indicate that you want everything else in the array, everything from the beginning of the array. For instance, if you want everything up to index 5, instead of specifying the starting parameter as 0, you can put my_array[:5], and this will return everything starts from the array to index 5. This is the same thing as calling syntax my_array[0:5].

Similarly, if you want to start at a particular index and grab the rest of the value up to the end of the array, you can use the same slicing notation, for example, my_array[5:].

# Broadcast

Numpy array is different from a standard Python list because of its ability to broadcast. Try to run this syntax my_array[0:5] = 100. This command is going to broadcast to those first five indexes to all be 100. On the other hand, you can create a new variable that equal to a certain slice from the original array.

In [51]:
my_array = np.arange(10, 100, 8)
print(my_array, '\n')

my_array[0:5] = 100
print(my_array)

[10 18 26 34 42 50 58 66 74 82 90 98] 

[100 100 100 100 100  50  58  66  74  82  90  98]


In [52]:
my_array = np.arange(10, 100, 8)
my_array_copy = my_array.copy()

print('Value from orginal my_array:\n{}'.format(my_array))

slice_of_array = my_array[0:6]
print('\nValue from slice_of_array:\n{}'.format(slice_of_array))

slice_of_array[:] = 100
print('\nslice_of_array new value:\n{}'.format(slice_of_array))

print('\nValue from original my_array:\n{}'.format(my_array))
print('\nValue from copy of my_array:\n{}'.format(my_array_copy))

Value from orginal my_array:
[10 18 26 34 42 50 58 66 74 82 90 98]

Value from slice_of_array:
[10 18 26 34 42 50]

slice_of_array new value:
[100 100 100 100 100 100]

Value from original my_array:
[100 100 100 100 100 100  58  66  74  82  90  98]

Value from copy of my_array:
[10 18 26 34 42 50 58 66 74 82 90 98]


If it is a little confusing for you, that is fine. The basic premise is that if you grab a slice of the array and set it as a variable without explicitly saying that you want a copy of the array, you should keep in mind that you are viewing a link to the original array. The changes you do will also affect the original array.

# Matrix Indexing

Now, we are going to talk about indexing a 2D array, otherwise known as a matrix. We have my_2d_array variable here, and we have 3 rows with 3 columns. It is a two-dimensional matrix. There are two general formats for grabbing elements from a 2D array or matrix. There are a double bracket format and a single bracket format with the comma, which is the recommended format to use.

In [53]:
my_2d_array = np.array([[25, 19, 46], [22, 38, 16], [86, 92, 53]])
print('Two-dimensional matrix:\n{}'.format(my_2d_array), '\n')

# Double bracket format
print('Double bracket format')
print(my_2d_array[0])
print(my_2d_array[0] [0])
print(my_2d_array[1] [1])
print(my_2d_array[2] [1])

# Single bracket format with comma
print('\nSingle bracket with comma')
print(my_2d_array[0])
print(my_2d_array[0, 0])
print(my_2d_array[1, 1])
print(my_2d_array[2, 1])


Two-dimensional matrix:
[[25 19 46]
 [22 38 16]
 [86 92 53]] 

Double bracket format
[25 19 46]
25
38
92

Single bracket with comma
[25 19 46]
25
38
92


Imagine that you did not want a single element, but actual chunks of the array. For instance, you want some matrices from the matrix. You can use a colon for slice notation to grab certain sections of the entire 2D array.

In [54]:
my_2d_array = np.array([[25, 19, 46], [22, 38, 16], [86, 92, 53]])
print('Two-dimensional matrix:\n{}'.format(my_2d_array), '\n')

# Chunk selection with slice notation
print('Chunk selection with slice notation:')
print(my_2d_array[:2, :], '\n')
print(my_2d_array[:, 1 :], '\n')
print(my_2d_array[:2, 1 :])


Two-dimensional matrix:
[[25 19 46]
 [22 38 16]
 [86 92 53]] 

Chunk selection with slice notation:
[[25 19 46]
 [22 38 16]] 

[[19 46]
 [38 16]
 [92 53]] 

[[19 46]
 [38 16]]


# Conditional Selection

We can grab some values of the array with a conditional selection through comparison operators.

In [57]:
my_array = np.arange(0, 11)

# Creating variable for the condition
bool_array = my_array > 5

print(my_array)
print(bool_array, '\n')

# Return condition array using variable
print('condition array using variable: \n{}'.format(my_array[bool_array]))

# Return condition array using argument
print('\ncondition array using argument: \n{}'.format(my_array[my_array >5]))
print(my_array[my_array < 3])


[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True  True] 

condition array using variable: 
[ 6  7  8  9 10]

condition array using argument: 
[ 6  7  8  9 10]
[0 1 2]


This process will return a full boolean array indicating true and false results. It is mean that if you compare the array to a single digit, for instance, my_array > 5, you will get an array of boolean values. So these are true or false values. It would return false wherever that comparison is false and true if that comparison was true. You can assign the comparison operators into variables and use them as a conditional selection.

# Operations

We are going to show you basic operation you can perform on NumPy arrays, such as array with array operations, the array with scalar operations, and some universal array functions. You can perform an array with array operations using simple arithmetic signs.

For instance, if you want to add two arrays together on elements by elements basis, you would say my_array + my_array. Essentially, every number’s been doubled. You can do the same process for subtraction or even multiplication.

You can also perform an array with scalar operations. For example, my_array + 100, scalar means a single number, and what NumPy does is broadcasts that number to every element in the array. This also works for multiplication, division, and subtraction. You can also do arrays with exponents, for example, my_array ** 2, this is the array to the power of two.
NumPy basic operation

In [58]:
my_array = np.arange(0, 11)
print(my_array, '\n')

print(my_array + my_array)
print(my_array - my_array)
print(my_array * my_array, '\n')

# Scalar operation 
print('Scalar array value with 100:\n{}'.format(my_array + 100))
print(my_array - 100)
print(my_array * 100)
print(my_array / 100, '\n')

# Exponential
print('Exponent array value:\n{}'.format(my_array ** 2))

[ 0  1  2  3  4  5  6  7  8  9 10] 

[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100] 

Scalar array value with 100:
[100 101 102 103 104 105 106 107 108 109 110]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[   0  100  200  300  400  500  600  700  800  900 1000]
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ] 

Exponent array value:
[  0   1   4   9  16  25  36  49  64  81 100]


Please Note:
Numpy will issue a warning instead of outputting errors on certain mathematical operations, however, you still get an output.For example, my_array / my_array.
Any array value divided by 0, will returns:[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
RuntimeWarning: invalid value encountered in true_divideOn the other hand, 1 / my_array.
If 1 divided by 0, you will also get a warning:[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ]
RuntimeWarning: divide by zero encountered in true_divide
In this case, it will show infinity instead of nan.

Numpy comes with many universal array functions, which are mostly just mathematical operations². You can use it to perform the action and broadcast it across the entire array. For instance, if you want to take the square root of every element in the array, you can say np.sqrt and then pass the array in the argument. This will make the square root of everything in the array.

Similarly, you can say np.exp and pass in the array into the argument for calculating the exponential. You can even use trigonometric functions such as sin and cos. This will pass every element into sin and cosine.

In [59]:
my_array = np.arange(0, 11)
print(my_array, '\n')

# Univerasl math operation
print('Square root and exponential:\n{}'.format(np.sqrt(my_array)))
print(np.exp(my_array))

# Trigonometric function
print('\nTrigonometric function:\n{}'.format(np.sin(my_array)))
print(np.cos(my_array))

[ 0  1  2  3  4  5  6  7  8  9 10] 

Square root and exponential:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]

Trigonometric function:
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]


# References
1 NumPy https://numpy.org/
2 Mathematical Function https://numpy.org/doc/stable/reference/routines.math.html
3 Cheat Sheet: Data Analysis in Python https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf
